Added config for deprecated 'HorizontalPodAutoscaler' apiversion
helm/helm-mapkubeapis pull request #69
Opened 2022-03-30 09:20 UTC by hydeenoble

deprecated "HorizontalPodAutoscaler" apiversion. 

The API Version is changed due to deprecated apiversion.
https://kubernetes.io/docs/reference/using-api/deprecation-guide/

2022-04-05 07:21 UTC, hickeyma requested changes
@hydeenoble  It looks like you didn't rebase with main. It seems you have pulled in pervious changes into this PR.

2022-04-05 07:25 UTC, hydeenoble commented
> @hydeenoble It looks like you didn't rebase with main. It seems you have pulled in pervious changes into this PR.

Yeah, that's what I did. What command should I run instead?

2022-08-18 14:57 UTC, hickeyma commented
@hydeenoble You need to rebase your branch with the latest main branch.

2022-08-21 10:45 UTC, hydeenoble commented
> @hydeenoble You need to rebase your branch with the latest main branch.

Done! @hickeyma

2022-08-22 09:57 UTC, hickeyma requested changes

2022-08-22 09:57 UTC, hickeyma commented on config/Map.yaml
> +    deprecatedInVersion: "v1.23"
Missing `removedInVersion` property

2022-08-23 17:27 UTC, hydeenoble commented on config/Map.yaml
> +    deprecatedInVersion: "v1.23"
Done!

2022-08-24 08:42 UTC, hickeyma requested changes
`.DS_Store` should not be part of the commit.

2022-08-24 09:32 UTC, hydeenoble commented
> `.DS_Store` should not be part of the commit.

Removed!. That was an oversight.

2022-08-24 13:12 UTC, hickeyma approved these changes
LGTM, thanks @hydeenoble

2022-08-24 13:13 UTC, merged