Bump Go, Helm and various dependencies
helm/helm-mapkubeapis pull request #87
Opened 2023-01-13 12:22 UTC by macedogm

Bump Go, Helm and various dependencies to fix CVEs flagged by Trivy.

Signed-off-by: Guilherme Macedo <guilherme.macedo@suse.com>

2023-01-13 12:25 UTC, macedogm commented
@mattfarina can you please take a look in this PR?

2023-01-17 18:17 UTC, hickeyma requested changes
Thanks @macedogm for pushing the updates. Small change and `mod tidy` and it should be good to go.

2023-01-17 18:17 UTC, hickeyma commented on go.mod
> +go 1.19
Leave at 1.18 to sync with Helm project

2023-01-17 18:20 UTC, hickeyma commented
Sorry but closing this @macedogm as #84 had the changes done previous to you.

2023-01-17 18:20 UTC, closed without merging

2023-01-17 18:24 UTC, macedogm commented
@hickeyma no problem in closing this PR and thanks for merging the other one 🙏🏻

2023-01-17 18:26 UTC, macedogm commented
@hickeyma forgot to ask, do you plan to cut a new release, please? If yes, when?